# Generated by Django 3.1.4 on 2021-04-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haq', '0014_auto_20210312_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data_status',
            field=models.CharField(default='-P-', max_length=3),
        ),
        migrations.AlterField(
            model_name='need',
            name='data_status',
            field=models.CharField(default='-P-', max_length=3),
        ),
        migrations.AlterField(
            model_name='reference',
            name='data_status',
            field=models.CharField(default='-P-', max_length=3),
        ),
        migrations.AlterField(
            model_name='religion',
            name='data_status',
            field=models.CharField(default='-P-', max_length=3),
        ),
        migrations.AlterField(
            model_name='status',
            name='data_status',
            field=models.CharField(default='-P-', max_length=3),
        ),
    ]
